// GENERATED by @edgedb/generate v0.0.8
// Run 'npx @edgedb/generate edgeql-js' to re-generate

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export type $PersonλShape = $.typeutil.flatten<_std.$Object_fe84743ee09e11edb375672f3ae9cdcdλShape & {
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
}>;
type $Person = $.ObjectType<"default::Person", $PersonλShape, null, [
  ..._std.$Object_fe84743ee09e11edb375672f3ae9cdcd['__exclusives__'],
]>;
const $Person = $.makeType<$Person>(_.spec, "4c5d4c20-e0e2-11ed-b455-91dc675792c2", _.syntax.literal);

const Person: $.$expr_PathNode<$.TypeSet<$Person, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Person, $.Cardinality.Many), null);



export { $Person, Person };

type __defaultExports = {
  "Person": typeof Person
};
const __defaultExports: __defaultExports = {
  "Person": Person
};
export default __defaultExports;
